site_name: Zz-709
site_url: https://zz-709.github.io/BLOG/
theme:
  name: material
features:
    - navigation.tabs
    - navigation.sections
nav:
  - 首页: index.md
  - 文章: docs/
markdown_extensions:
  - toc:
      permalink: true
